import OpenAI from "openai";
import fs from "fs";
import path from "path";
import { v4 as uuidv4 } from "uuid";
import { GoogleGenerativeAI } from "@google/generative-ai";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
});

// Initialize the Gemini SDK
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

export async function generateImage(post) {

  const prompt = `Soft hand-drawn minimal illustration of a ${post.breed}, ${post.furColor} fur color. Scene: ${post.imagePrompt}. Light neutral background, calm storytelling mood, 1080x1080 square, no text.`;

  const fileName = `${uuidv4()}.png`;
  const filePath = path.join("/tmp", fileName);

  // 1️⃣ TRY OPENAI FIRST
  try {
    console.log("🖼 Trying OpenAI (DALL-E 3)...");
    const response = await openai.images.generate({
      model: "dall-e-3",
      prompt,
      size: "1024x1024",
      response_format: "b64_json"
    });

    const imageBase64 = response.data[0].b64_json;
    fs.writeFileSync(filePath, Buffer.from(imageBase64, "base64"));
    console.log("✅ Success: Image generated by OpenAI.");
    return { imagePath: filePath, provider: "OpenAI" };

  } catch (openaiError) {
    console.log(`⚠️ OpenAI failed (${openaiError.message}). Switching to Google Imagen...`);

    // 2️⃣ FALLBACK TO GOOGLE IMAGEN 3
    try {
      // NOTE: Standard Gemini models (Flash/Pro) DO NOT generate images via generateContent.
      // You MUST use the specific Imagen model.
      const model = genAI.getGenerativeModel({ model: "imagen-3.0-generate-001" });

      const result = await model.generateImages({
        prompt: prompt,
        numberOfImages: 1,
        // Optional configuration for social media
        aspectRatio: "1:1",
      });

      // Ensure an image was actually returned
      if (!result.generatedImages || result.generatedImages.length === 0) {
        throw new Error("Imagen returned no images. Check safety filters or prompt.");
      }

      const imageBytes = result.generatedImages[0].image.imageBytes;
      // Google returns raw bytes; write them to a file
      fs.writeFileSync(filePath, Buffer.from(imageBytes, "base64"));

      console.log("✅ Success: Image generated by Google Imagen 3.");
      return { imagePath: filePath, provider: "Google" };

    } catch (googleError) {
      console.error("❌ Both providers failed.");
      console.error("Google Error Details:", googleError.message);
      throw googleError;
    }
  }
}
