import OpenAI from "openai";
import fs from "fs";
import path from "path";
import { v4 as uuidv4 } from "uuid";
import { GoogleGenerativeAI } from "@google/generative-ai";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
});

// Initialize Gemini
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

export async function generateImage(post) {

  const prompt = `Soft hand-drawn minimal illustration of a ${post.breed}, ${post.furColor} fur color. Scene: ${post.imagePrompt}. Light neutral background, calm mood, 1080x1080, no text.`;

  const fileName = `${uuidv4()}.png`;
  const filePath = path.join("/tmp", fileName);

  // 1️⃣ TRY OPENAI FIRST
  try {
    console.log("🖼 Trying OpenAI (DALL-E 3)...");
    const response = await openai.images.generate({
      model: "dall-e-3",
      prompt,
      size: "1024x1024",
      response_format: "b64_json"
    });

    const imageBase64 = response.data[0].b64_json;
    fs.writeFileSync(filePath, Buffer.from(imageBase64, "base64"));
    return { imagePath: filePath, provider: "OpenAI" };

  } catch (openaiError) {
    console.log(`⚠️ OpenAI failed: ${openaiError.message}. Switching to Google Imagen...`);

    // 2️⃣ FALLBACK TO GOOGLE IMAGEN 3
    try {
      // Imagen 3 is the dedicated image model in the Google AI ecosystem
      const model = genAI.getGenerativeModel({ model: "imagen-3.0-generate-001" });

      // Imagen uses a different structure than Gemini text models
      const result = await model.generateImages({
        prompt: prompt,
        numberOfImages: 1,
        aspectRatio: "1:1",
        safetySettings: [
          {
            category: "HARM_CATEGORY_HARASSMENT",
            threshold: "BLOCK_LOW_AND_ABOVE",
          }
        ],
      });

      const imageBytes = result.generatedImages[0].image.imageBytes;
      fs.writeFileSync(filePath, Buffer.from(imageBytes, "base64"));

      console.log("✅ Success: Image generated by Google Imagen.");
      return { imagePath: filePath, provider: "Google" };

    } catch (googleError) {
      console.error("❌ All image generation providers failed.");
      console.error("Google Error:", googleError.message);
      throw googleError;
    }
  }
}
