import OpenAI from "openai";
import fs from "fs";
import path from "path";
import { v4 as uuidv4 } from "uuid";
import axios from "axios";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
});

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

export async function generateImage(post) {

  const prompt = `Soft hand-drawn minimal illustration of a ${post.breed}, ${post.furColor} fur color. Scene: ${post.imagePrompt}. Light neutral background, 1080x1080 square, no text.`;

  const fileName = `${uuidv4()}.png`;
  const filePath = path.join("/tmp", fileName);

  // 1️⃣ TRY OPENAI FIRST
  try {
    console.log("🖼 Trying OpenAI (DALL-E 3)...");
    const response = await openai.images.generate({
      model: "dall-e-3",
      prompt,
      size: "1024x1024",
      response_format: "b64_json"
    });

    const imageBase64 = response.data[0].b64_json;
    fs.writeFileSync(filePath, Buffer.from(imageBase64, "base64"));
    console.log("✅ Success: Image generated by OpenAI.");
    return { imagePath: filePath, provider: "OpenAI" };

  } catch (openaiError) {
    console.log(`⚠️ OpenAI failed (${openaiError.message}). Switching to Gemini (REST)...`);

    // 2️⃣ FALLBACK TO GEMINI (Using your proven Blog Logic)
    try {
      // We use gemini-2.5-flash-image which is the current stable model for this
      const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent?key=${GEMINI_API_KEY}`;
      
      const res = await axios.post(url, {
        contents: [{ 
          parts: [{ text: prompt }] 
        }],
        generationConfig: {
          responseModalities: ["IMAGE"]
        }
      });

      // Extract the image data from the response structure
      const imageData = res.data.candidates[0].content.parts.find(p => p.inlineData)?.inlineData.data;
      
      if (!imageData) {
        throw new Error("No image data returned from Gemini. Check safety filters.");
      }

      fs.writeFileSync(filePath, Buffer.from(imageData, "base64"));
      console.log("✅ Success: Image generated by Gemini.");
      return { imagePath: filePath, provider: "Gemini" };

    } catch (geminiError) {
      console.error("❌ Both providers failed.");
      console.error("Gemini Details:", geminiError.message);
      throw geminiError;
    }
  }
}
